services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "4317:4317"
      - "4318:4318"
    command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - ./tls.conf:/etc/nginx/conf.d/tls.conf
      - ./server.crt:/tmp/server.crt
      - ./server.key:/tmp/server.key
  otel:
    image: otel/opentelemetry-collector-contrib:0.95.0
    container_name: otlp
    command: ["--config=/etc/otel-sample.yaml"]
    ports:
      - "4317"   # grpc
      - "4318"   # http
    volumes:
      - ./otel-sample.yaml:/etc/otel-sample.yaml
